source 'http://gemcutter.org'
# Base requirements
gem 'sinatra'
gem 'sinatra_more'
gem 'rack-flash'
gem 'warden'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'actionmailer', :require => 'action_mailer'

# Component requirements

# Testing requirements
gem 'rack-test', :require => 'rack/test', :group => :testing